name: black-action
on: [push, pull_request]
jobs:
  linter_name:
    name: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python -V
      - run: python -m pip install black
      - run: black .
