name: First Workflow
on: push
jobs:
  prepare_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python -V
      - run: python -m pip install pytest pytest-cov
      - run: pytest --cov -cov_report=xml:coverage.xml ./tests
